{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "network-latency-exporter.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "network-latency-exporter.name" . }}
{{- end -}}
