version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  commit-message:
    prefix: chore
    prefix-development: chore
    include: scope
  groups:
    actions-deps:
      patterns:
        - "*"
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
  commit-message:
    prefix: chore
    prefix-development: chore
    include: scope
  groups:
    k8s.io:
      patterns:
      - "k8s.io/*"
      - "sigs.k8s.io/*"
    go.opentelemetry.io:
      patterns:
      - "go.opentelemetry.io/*"
    prometheus:
      patterns:
      - "github.com/prometheus/*"
  open-pull-requests-limit: 20
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "weekly"
  commit-message:
    prefix: chore
    prefix-development: chore
    include: scope
  groups:
    actions-deps:
      patterns:
        - "*"
