---

quiet: true

skip-check:
# https://www.checkov.io/5.Policy%20Index/kubernetes.html
- CKV_K8S_15 # Image Pull Policy should be Always
- CKV_K8S_21 # The default namespace should not be used. (This rule not best practices: https://github.com/bridgecrewio/checkov/issues/3910)
- CKV_K8S_38 # Ensure that Service Account Tokens are only mounted where necessary. (Temporarily skipped due to testing complexity. Consider switching to temporary tokens https://adil.medium.com/how-to-use-tokenrequest-api-and-tokenvolume-projection-in-kubernetes-f007135b9994)
- CKV_K8S_43 # Image should use digest. (Requires a common target approach)
- CKV2_K8S_6 # Minimize the admission of pods which lack an associated NetworkPolicy
# https://www.checkov.io/5.Policy%20Index/github_actions.html
- CKV2_GHA_1 # Ensure top-level permissions are not set to write-all. (It is not possible to reduce the minimum rights for third-party services)
- CKV_GHA_7 # The build output cannot be affected by user parameters other than the build entry point and the top-level source location. GitHub Actions workflow_dispatch inputs MUST be empty.
